# Project: DuAn_Game
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = DuAn_Game.o
LINKOBJ  = DuAn_Game.o
LIBS     = -L"D:/THvsC/CTDLGT/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -lbgi  -lgdi32 -m32
INCS     = -I"D:/THvsC/CTDLGT/Dev-Cpp/MinGW64/include" -I"D:/THvsC/CTDLGT/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/THvsC/CTDLGT/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/THvsC/CTDLGT/Dev-Cpp/MinGW64/include" -I"D:/THvsC/CTDLGT/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/THvsC/CTDLGT/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/THvsC/CTDLGT/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = DuAn_Game.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

DuAn_Game.o: DuAn_Game.cpp
	$(CPP) -c DuAn_Game.cpp -o DuAn_Game.o $(CXXFLAGS)
